name: Build by Image Builder
run-name: Image Builder - ${{ inputs.version }} - ${{ inputs.target }}

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      target:
        type: string
        description: 'Target architecture'
        required: true
        default: 'x86/64'
      version:
        type: string
        description: 'Release version'
        required: true
      profile:
        type: string
        description: 'Profile of target, `make info` to view available profiles'
        required: false
      rootfs_partsize:
        type: number
        description: 'Root partition size'
        required: true
        default: 1024
      build_iso_images:
        type: boolean
        description: 'Build ISO images'
        required: true
        default: false
      build_qcow2_images:
        type: boolean
        description: 'Build QCOW2 images'
        required: true
        default: false
      build_vdi_images:
        type: boolean
        description: 'Build VDI images'
        required: true
        default: false
      build_vmdk_images:
        type: boolean
        description: 'Build VMDK images'
        required: true
        default: false
      build_vhdx_images:
        type: boolean
        description: 'Build VHDX images'
        required: true
        default: false
      upload_2_release:
        type: boolean
        description: 'Upload to release'
        required: true
        default: false

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  FEEDS_CONF: feeds.conf.default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update -y
        sudo -E apt-get purge -y --ignore-missing --autoremove azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby*
        sudo -E apt-get install -y --no-install-recommends --no-install-suggests ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
          libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
          ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
          upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        root-reserve-mb: 4096
        swap-size-mb: 4096

    - name: Load custom feeds
      run: |
        if [ -e $FEEDS_CONF ]; then
            cat $FEEDS_CONF imagebuilder/repositories.conf > repositories_tmp.conf
            mv repositories_tmp.conf imagebuilder/repositories.conf
        fi

    - name: Download Image Builder
      run: |
        TARGET_NAME=$(echo "${{ inputs.target }}" | sed 's/\//_/g')
        echo "TARGET_NAME=${TARGET_NAME}" >> $GITHUB_ENV
        ARCH=$(echo "${{ inputs.target }}" | cut -d '/' -f1 )
        SUBARCH=$(echo "${{ inputs.target }}" | cut -d '/' -f2- )
        # immortalwrt-imagebuilder-24.10.6-x86-64.Linux-x86_64.tar.zst
        IMAGE_BUILDER_FILE_NAME="immortalwrt-imagebuilder-${{ inputs.version }}-${ARCH}-${SUBARCH}.Linux-${TARGET_NAME}.tar.zst"
        wget https://downloads.immortalwrt.org/releases/${{ inputs.version }}/targets/${ARCH}/${SUBARCH}/${IMAGE_BUILDER_FILE_NAME}
        mkdir imagebuilder
        tar --zstd -xf ${IMAGE_BUILDER_FILE_NAME} -C imagebuilder --strip-components 1

    - name: Build image
      run: |
        cd imagebuilder
        # Modify .config based on user inputs if needed
        if [ "${{ inputs.build_iso_images }}" == "false" ]; then
          sed -i 's/CONFIG_ISO_IMAGES=y//' .config
        fi
        if [ "${{ inputs.build_qcow2_images }}" == "false" ]; then
          sed -i 's/CONFIG_QCOW2_IMAGES=y//' .config
        fi
        if [ "${{ inputs.build_vdi_images }}" == "false" ]; then
          sed -i 's/CONFIG_VDI_IMAGES=y//' .config
        fi
        if [ "${{ inputs.build_vmdk_images }}" == "false" ]; then
          sed -i 's/CONFIG_VMDK_IMAGES=y//' .config
        fi
        if [ "${{ inputs.build_vhdx_images }}" == "false" ]; then
          sed -i 's/CONFIG_VHDX_IMAGES=y//' .config
        fi
        PROFILE="${{ inputs.profile }}"
        make image ${PROFILE:+PROFILE="${PROFILE}"} \
          ROOTFS_PARTSIZE=${{ inputs.rootfs_partsize }} \
          PACKAGES="bind-dig dnsmasq-full curl darkstat iftop ip-full librespeed-go luci-app-cloudflared \
            luci-app-dockerman luci-app-passwall luci-app-pbr luci-app-ttyd luci-app-upnp luci-app-vlmcsd \
            luci-app-wol nano-full nexttrace parted resize2fs tcpdump wget-ssl" --trace

    - name: Set build variables
      run: |
        cd imagebuilder/bin/targets/*/*
        FILE_DATE=$(date -u +"%Y%m%dT%H%M%SZ")
        VERSION="v${{ inputs.version }}_${{ env.TARGET_NAME }}_$(cat version.buildinfo)_imagebuilder"
        echo "OUTPUT_NAME=${VERSION}_${FILE_DATE}" >> $GITHUB_ENV
        echo "OUTPUT_PATH=$(echo $PWD)" >> $GITHUB_ENV

    - name: Upload to artifact
      uses: actions/upload-artifact@v4
      with:
        name: ImmortalWrt_${{ env.OUTPUT_NAME }}
        path: |
          ${{ env.OUTPUT_PATH }}
        if-no-files-found: error

    - name: Upload to release
      uses: softprops/action-gh-release@v2.0.8
      if: env.UPLOAD_2_RELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.OUTPUT_NAME }}
        body: ${{ env.OUTPUT_NAME }}
        files: |
          ${{ env.OUTPUT_PATH }}/*

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.4
      if: env.UPLOAD_2_RELEASE == 'true'
      with:
        keep_latest: 3
        delete_tag_pattern: ^v${{ inputs.version }}_${{ env.TARGET_NAME }}
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
